import { expect, test } from './fixtures';

test('custom keys persist, reject conflicts, and stay in tooltips', async ({ page }) => {
  await page.goto('/');
  const left = page.getByRole('textbox', { name: 'left editor', exact: true });
  await expect(left).toBeEnabled();
  await left.fill('one    two');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: /Keys/ }).click();
  const search = page.getByRole('textbox', { name: 'Search actions' });
  await search.fill('Spaces');
  const record = page.getByRole('button', { name: 'Assign shortcut: Spaces', exact: true });
  await expect(record).toBeEnabled();
  await record.click();
  await page.keyboard.press('Control+Shift+K');
  await expect(record).toHaveText('Ctrl + Shift + K');
  await expect(page.getByText('Shortcut saved.', { exact: true })).toBeVisible();
  await search.fill('History');
  await page.getByRole('button', { name: 'Assign shortcut: History', exact: true }).click();
  await page.keyboard.press('Control+Shift+K');
  await expect(page.getByRole('alert')).toContainText('already assigned');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog', { name: 'Keyboard shortcuts' })).toBeVisible();
  await page.getByRole('button', { name: 'Close Settings' }).click();
  await left.focus();
  await page.keyboard.press('Control+Shift+K');
  await expect(left).toHaveValue('one two');
  const spaces = page.getByRole('button', { name: 'Spaces', exact: true });
  await expect(spaces).toHaveAttribute('title', 'Spaces (Ctrl + Shift + K)');
  await expect(spaces).toHaveText('Spaces');
  await page.reload();
  await expect(left).toBeEnabled();
  await expect(spaces).toHaveAttribute('title', 'Spaces (Ctrl + Shift + K)');
  await left.fill('three    four');
  await page.keyboard.press('Control+Shift+K');
  await expect(left).toHaveValue('three four');
  await page.keyboard.press('Control+z');
  await expect(left).toHaveValue('three    four');
  await page.keyboard.press('Control+f');
  await expect(page.getByRole('textbox', { name: 'Find in text' })).toBeFocused();
  await page.getByRole('textbox', { name: 'Find in text' }).fill('one   two');
  await page.keyboard.press('Control+Shift+K');
  await expect(left).toHaveValue('three    four');
  await page.getByRole('button', { name: 'Close search' }).click();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: /Keys/ }).click();
  await search.fill('Spaces');
  await page.getByRole('button', { name: 'Reset shortcut: Spaces', exact: true }).click();
  await expect(record).toHaveText('Assign shortcut');
});
