import { expect, test } from './fixtures';

test('find, exact tag navigation, and copying preserve text and independent undo', async ({ page }) => {
  await page.goto('/');
  const left = page.getByRole('textbox', { name: 'left editor', exact: true });
  const right = page.getByRole('textbox', { name: 'right editor', exact: true });
  await expect(left).toBeEnabled();
  const original = '[Chorus]\n' + 'Long line of text\n'.repeat(80) + '[Chorus]\nEnding';
  await right.fill('Keep this version');
  await left.fill(original);
  await page.getByRole('button', { name: 'Search left editor', exact: true }).click();
  await page.getByRole('textbox', { name: 'Find in text' }).fill('[Chorus]');
  await expect(page.getByText('1 of 2', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Next match' }).click();
  await expect(page.getByText('2 of 2', { exact: true })).toBeVisible();
  expect(await left.evaluate((el: HTMLTextAreaElement) => [el.selectionStart, el.scrollTop > 0])).toEqual([original.lastIndexOf('[Chorus]'), true]);
  await expect(left).toHaveValue(original);
  await page.getByRole('button', { name: 'Close search' }).click();
  await page.getByRole('button', { name: 'Copy left text to other editor' }).click();
  await expect(right).toHaveValue(original);
  await expect(left).toHaveValue(original);
  await right.locator('..').locator('..').getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(right).toHaveValue('Keep this version');
  await left.focus();
  await page.getByRole('button', { name: 'Suno', exact: true }).click();
  await page.getByRole('button', { name: 'Tags', exact: true }).click();
  await page.getByRole('button', { name: 'Go to tag 2: [Chorus]', exact: true }).click();
  expect(await left.evaluate((el: HTMLTextAreaElement) => el.selectionStart)).toBe(original.lastIndexOf('[Chorus]'));
  await expect(left).toHaveValue(original);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Go to tag 1: [Chorus]', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Suno Tags' })).toBeHidden();
  await expect(left).toBeVisible();
  await page.setViewportSize({ width: 844, height: 393 });
  await page.getByRole('button', { name: 'Tags', exact: true }).click();
  await page.getByRole('button', { name: 'Go to tag 2: [Chorus]', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Suno Tags' })).toBeHidden();
  await expect(left).toBeVisible();
});
